/* League reads stay in the browser. The forecast engine runs off the main thread. */
(function(){'use strict';if(!window.GW_WEEKLY_MODE)return;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=x=>(100*x).toFixed(1)+'%',num=x=>Number.isFinite(x)?x.toFixed(1):'—',cash=x=>'$'+Math.round(x),KEY='dd-guillotine-weekly-v1';
let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{saved={};}let league,rosters,users,feed,result,players,transactions,focusResult,schedule,excluded=[],generation=0,focusGeneration=0,seq=0,pending=new Map();
let loadingLeague=null;let worker;function startWorker(){if(worker)return;worker=new Worker('/guillotine-compute.js');worker.onmessage=e=>{const p=pending.get(e.data.id);if(!p)return;pending.delete(e.data.id);e.data.error?p.reject(Error(e.data.error)):p.resolve(e.data.result);};worker.onerror=()=>{for(const p of pending.values())p.reject(Error('Calculation worker failed. Refresh to retry.'));pending.clear();};}
function calc(op,payload){startWorker();return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});worker.postMessage({id,op,payload});});}
function save(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}}
function error(e){$('gwError').hidden=false;$('gwError').textContent=e.message||e;}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('Data request failed ('+r.status+')');return r.json();}
function name(rid){const r=rosters?.find(x=>String(x.roster_id)===String(rid)),u=users?.find(x=>x.user_id===r?.owner_id);return u?.metadata?.team_name||u?.display_name||'Roster '+rid;}
function table(head,rows){return '<table><thead><tr>'+head.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>';}
function metric(v,k){return '<div class="gw-metric"><b>'+v+'</b><span>'+k+'</span></div>';}
function setStatus(s){$('gwStatus').textContent=s;}
function choice(){return $('gwFocus').value;}
async function load(){const token=++generation;++focusGeneration;result=null;focusResult=null;for(const id of ['gwMetrics','gwBoard','gwChop','gwLineup','gwWaivers','gwWeak','gwBudgets','gwBids','gwOutlook','gwReceipts'])$(id).textContent='';$('gwError').hidden=true;$('gwLoad').disabled=true;setStatus('Reading league, weekly players, budgets and transactions…');try{
 const id=$('gwLeague').value.match(/\d{6,24}/)?.[0];if(!id)throw Error('Enter a Sleeper league ID');
 const [l,r,u,f,st,sc,cal]=await Promise.all([get('https://api.sleeper.app/v1/league/'+id),get('https://api.sleeper.app/v1/league/'+id+'/rosters'),get('https://api.sleeper.app/v1/league/'+id+'/users'),get('/data/guillotine-weekly.json'),get('https://api.sleeper.app/v1/state/nfl'),get('/data/nfl-schedule.json'),get('/data/guillotine-calibration.json')]);
 f.data={...f.data,calibrations:cal.data.league_calibrations||f.data.calibrations};
 if(!l||!Array.isArray(r))throw Error('League not found');if(l.settings.type!==3)throw Error('This release requires a Sleeper Chopped league');
 if(f.data.season!==Number(l.season)||f.data.week!==Math.max(1,Math.min(18,st.display_week)))throw Error('The daily player feed is not for this league’s current week. Forecasts are withheld until it refreshes.');
 if(!Number.isFinite(Date.parse(f.data.fetched_at))||Date.now()-Date.parse(f.data.fetched_at)>48*3600000)throw Error('Weekly inputs are over 48 hours old. Forecasts are withheld.');
 const tx=await Promise.all(Array.from({length:f.data.week},(_,i)=>get('https://api.sleeper.app/v1/league/'+id+'/transactions/'+(i+1))));if(token!==generation)return;
 $('gwSleeperLink').href='https://sleeper.com/leagues/'+id+'/team';league=l;rosters=r;users=u;feed={...f.data,calibration:GXEngine.calibrationFor(f.data,l)};transactions=tx.flat();schedule=sc.data.games;
 excluded=(saved[id]?.excluded)||r.filter(x=>feed.week>1&&!(x.players||[]).length).map(x=>String(x.roster_id));
 $('gwFocus').innerHTML='<option value="">Choose your team</option>'+r.map(x=>'<option value="'+x.roster_id+'">'+esc(name(x.roster_id))+'</option>').join('');$('gwFocus').value=saved[id]?.focus||'';
 saved.last=id;saved[id]={...saved[id],name:l.name};save();$('gwSaved').innerHTML='<option value="">Saved leagues</option>'+Object.keys(saved).filter(k=>/^\d+$/.test(k)).map(k=>'<option value="'+k+'">'+esc(saved[k].name||k)+'</option>').join('');
 setStatus('Simulating current starting lineups…');const loaded=await calc('load',{feed,league,rosters,transactions,excluded,now:Date.now()});if(token!==generation)return;result=loaded;players=result.players;render();await selectFocus();
 setStatus(l.name+' · Week '+feed.week+' · '+r.length+' rosters · fetched '+new Date(feed.fetched_at).toLocaleString()+' · '+result.n.toLocaleString()+' simulations. Refresh after roster changes.');
 }catch(e){if(token!==generation)return;error(e);$('gwMetrics').innerHTML='';$('gwBoard').innerHTML='Forecast unavailable. Resolve the data issue above.';for(const id of ['gwLineup','gwWaivers','gwOutlook'])$(id).textContent='Forecast unavailable: '+(e.message||e);setStatus('No new forecast published.');}finally{if(token===generation)$('gwLoad').disabled=false;}}
function render(){const alive=rosters.filter(r=>!excluded.includes(String(r.roster_id))),pool=alive.reduce((s,r)=>s+GXEngine.budget(r,league),0);
 $('gwMetrics').innerHTML=metric(result.active.length,'Surviving teams')+metric(num(result.chop),'Median chop line')+metric(cash(pool),'FAAB left in the field')+metric('Week '+feed.week,'Weekly projections');
 $('gwBoard').innerHTML=table(['Rank / team','Survive','Projected score','80% score range'],result.rows.map((r,i)=>'<tr data-rid="'+r.rid+'"><td>'+(i+1)+'. '+esc(name(r.rid))+'</td><td><span class="bar"><i style="width:'+100*r.survival+'%"></i></span>'+pct(r.survival)+'</td><td>'+num(r.mean)+'</td><td>'+num(r.lo)+' – '+num(r.hi)+'</td></tr>'));
 $('gwBoard').querySelectorAll('[data-rid]').forEach(tr=>tr.onclick=()=>{$('gwFocus').value=tr.dataset.rid;selectFocus();});
 const lo=Math.max(0,result.lo-20),hi=result.hi+20,x=v=>30+Math.max(0,Math.min(1,(v-lo)/(hi-lo)))*620;
 $('gwChop').innerHTML='<svg viewBox="0 0 680 105" role="img" aria-label="Modeled chop line 80 percent range '+num(result.lo)+' to '+num(result.hi)+'"><line x1="30" y1="45" x2="650" y2="45" stroke="currentColor" opacity=".2" stroke-width="10"/><line x1="'+x(result.lo)+'" y1="45" x2="'+x(result.hi)+'" y2="45" stroke="#b34b05" stroke-width="14" stroke-linecap="round"/><circle cx="'+x(result.chop)+'" cy="45" r="12" fill="#573019"/><text x="'+x(result.lo)+'" y="84" text-anchor="middle" fill="currentColor">'+num(result.lo)+'</text><text x="'+x(result.chop)+'" y="20" text-anchor="middle" fill="currentColor">Median '+num(result.chop)+'</text><text x="'+x(result.hi)+'" y="84" text-anchor="middle" fill="currentColor">'+num(result.hi)+'</text></svg>';
 $('gwBudgets').innerHTML=table(['Team','Remaining','Share of active cash'],alive.slice().sort((a,b)=>GXEngine.budget(b,league)-GXEngine.budget(a,league)).map(r=>'<tr><td>'+esc(name(r.roster_id))+'</td><td>'+cash(GXEngine.budget(r,league))+'</td><td>'+(pool?pct(GXEngine.budget(r,league)/pool):'—')+'</td></tr>'));
 const bids=transactions.filter(t=>t.type==='waiver'&&t.status==='complete'&&t.settings?.waiver_bid!=null);
 $('gwBids').innerHTML=bids.length?table(['Player','Winning bid','Processed'],bids.slice(-25).reverse().map(t=>'<tr><td>'+Object.keys(t.adds||{}).map(id=>esc(players[id]?.name||id)).join(', ')+'</td><td>'+cash(t.settings.waiver_bid)+'</td><td>'+new Date(t.status_updated).toLocaleDateString()+'</td></tr>')):'No completed waiver bids yet. Free-agent adds are not evidence of auction prices. Dollar cost estimates will appear after enough same-position winning bids exist.';
 $('gwMethod').innerHTML='<p class="gw-note">Model '+GXEngine.VERSION+' · '+feed.calibration.sample_n+' historical player games · '+feed.calibration.history_season+'. '+esc(feed.calibration.method)+'</p><p class="gw-note">'+esc(feed.calibration.limitation)+'</p><p class="gw-note">League scoring: '+esc(JSON.stringify(feed.calibration.scoring))+'</p>';
 $('gwActive').innerHTML=rosters.map(r=>'<label style="display:inline-block;padding:8px"><input type="checkbox" data-active="'+r.roster_id+'" '+(!excluded.includes(String(r.roster_id))?'checked':'')+'> '+esc(name(r.roster_id))+'</label>').join('');
 receipts();history();}
async function selectFocus(){if(!result)return;const rid=choice();saved[league.league_id]={...saved[league.league_id],focus:rid};save();if(!rid){++focusGeneration;focusResult=null;$('gwWeak').textContent='';$('gwLineup').textContent='Choose your team.';$('gwWaivers').textContent='Choose your team.';return;}if(!result.active.includes(Number(rid))){++focusGeneration;focusResult=null;$('gwWaivers').textContent='This team is excluded as eliminated.';$('gwWeak').textContent='';$('gwLineup').textContent='This team is excluded as eliminated.';return;}
 const token=++focusGeneration;focusResult=null;$('gwLineup').textContent='Testing legal lineups against the surviving field…';$('gwWaivers').textContent='Evaluating free agents, required drops and competing roster needs…';try{const f=await calc('focus',{rid,capFraction:Number($('gwCap').value)/100});if(choice()!==rid||token!==focusGeneration)return;focusResult=f;const r=rosters.find(r=>String(r.roster_id)===rid),b=f.optimized.best;
 if(!b){$('gwLineup').textContent='No complete legal lineup with the current kickoff locks. Fill missing eligible positions in Sleeper.';$('gwWaivers').textContent='Fill missing positions before comparing upgrades.';return;}
 $('gwLineup').innerHTML='<div class="gw-metrics">'+metric(pct(f.current.survival),'Current lineup survival')+metric(pct(b.survival),'Best tested lineup survival')+metric(((b.survival-f.current.survival)*100).toFixed(1)+' pp','Modeled improvement')+'</div><div class="gw-scroll">'+table(['Slot','Suggested starter','Projected','Action'],b.ids.map((id,i)=>{const p=players[id];if(!p)return '<tr><td>'+esc(GXEngine.slots(league)[i])+'</td><td>Empty — add an eligible player</td><td>0.0</td><td>Needs coverage</td></tr>';return '<tr><td>'+esc(GXEngine.slots(league)[i])+'</td><td>'+esc(p.name)+'<small>'+esc(p.team+' vs '+(p.opponent||'bye')+(p.injury?' · '+p.injury:''))+'</small></td><td>'+num(p.mean)+'</td><td>'+(p.started?'Locked':r.starters.includes(id)?'Keep starting':'Start; replace '+esc(players[r.starters[i]]?.name||'empty slot'))+'</td></tr>';}))+'</div><p class="gw-note">'+f.optimized.tested.toLocaleString()+' legal lineups tested'+(f.optimized.truncated?' (search cap reached; not a guaranteed global optimum)':'')+'. Tiny differences can be simulation noise; this is not a guarantee of survival.</p>';
 $('gwWeak').innerHTML=(r.players||[]).map(id=>players[id]).filter(p=>p&&(p.injury||!p.opponent||p.mean<2&&r.starters.includes(p.id))).map(p=>'<p>'+esc(p.name)+' — '+esc(p.injury||(!p.opponent?'No game this week':'Low weekly projection'))+'</p>').join('')||'No injury, bye or very-low-projection starter flags in this feed.';
 const p=f.plan;$('gwWaivers').innerHTML='<div class="gw-metrics">'+metric(cash(p.left),'Your remaining FAAB')+metric(cash(p.cap),'Cycle spending limit')+metric(cash(p.reserve),'Reserve if limit is spent')+'</div><p class="gw-note">Each row is an alternative acquisition, not a shopping list to submit together. Survival gain is versus your optimized current roster. Suggested drops prioritize this week and can sacrifice future value; inspect the season view first.</p><div class="gw-scroll">'+table(['Add / drop','Survival gain','Estimated demand','Historical cost','Planning ceiling'],p.rows.map(x=>'<tr><td>'+esc(players[x.id].name)+'<small>Drop '+esc(players[x.drop]?.name||x.drop)+'</small></td><td>+'+(x.delta*100).toFixed(1)+' pp<small>'+pct(x.survival)+' after add</small></td><td>'+x.competitors+' roster fits<small>Largest rival budget '+cash(x.maxRival)+'</small></td><td>'+(x.cost?cash(x.cost[0])+'–'+cash(x.cost[1]):'Not enough bids')+'<small>'+x.bidN+' same-position winners</small></td><td>'+cash(x.valueCap)+'<small>'+(x.suggested==null?'No evidence-based bid yet':'Consider up to '+cash(x.suggested))+'</small></td></tr>'))+'</div>'+(p.rows.length?'':'<p>No available candidate improves modeled weekly survival after a legal drop.</p>')+'<p class="gw-note">'+p.screened+' lineup-fit free agents screened; top '+p.evaluated+' evaluated for survival. Planning ceiling scales your chosen cycle budget by the fraction of chop risk removed. It is a disclosed budgeting heuristic, not a fair market price. $0 bids remain legal.</p>';
 }catch(e){if(token!==focusGeneration)return;error(e);$('gwLineup').textContent='Calculation unavailable.';$('gwWaivers').textContent='Calculation unavailable.';}}
async function history(){try{const e=await get('/data/guillotine-market-history.json'),h=e.data;$('gwHistory').innerHTML='<p class="gw-note">'+esc(h.name)+' · '+h.season+' · '+h.completed_winning_bids+' completed winning bids · '+h.reception_points+' points/reception · original budget '+cash(h.starting_faab)+'. Separate reference, not your league’s prices.</p><div class="gw-scroll">'+table(['Season stage','Winners','Median / original budget','Middle 50%'],h.stages.map(x=>'<tr><td>'+esc(x.stage)+'</td><td>'+x.n+'</td><td>'+pct(x.median_fraction)+'</td><td>'+pct(x.p25_fraction)+'–'+pct(x.p75_fraction)+'</td></tr>'))+'</div><p class="gw-note">'+esc(h.limitations)+'</p>';}catch{$('gwHistory').textContent='Historical market reference unavailable.';}}
async function receipts(){try{const e=await get('/data/guillotine-receipts.json'),r=e.data.filter(x=>x.league_id===league.league_id);$('gwReceipts').innerHTML=r.length?table(['Week','Captured','State','Multiclass Brier'],r.map(x=>'<tr><td>'+x.week+'</td><td>'+new Date(x.captured_at).toLocaleString()+'</td><td>'+esc(x.status)+'</td><td>'+num(x.brier)+'</td></tr>')):'No prospective forecasts captured yet. The next eligible daily run starts the record.';}catch{$('gwReceipts').textContent='The forecast ledger is unavailable; no performance claim is made.';}}
async function season(){if(!result)return;$('gwSeason').disabled=true;$('gwOutlook').textContent='Simulating the fixed-roster scenario with future byes…';try{
 const active=rosters.filter(r=>result.active.includes(r.roster_id)),last=Math.min(18,feed.week+active.length-2),n=800,byes={};
 for(let w=feed.week;w<=last;w++){const teams=new Set(schedule.filter(g=>g.season===feed.season&&g.week===w).flatMap(g=>[g.home_team,g.away_team].map(t=>({LA:'LAR',OAK:'LV'}[t]||t))));byes[w]=teams;}
 const scores={},holes=[];for(let w=feed.week;w<=last;w++){const p={};for(const [id,x] of Object.entries(players))p[id]={...x,started:false,unavailable:x.unavailable||!byes[w].has(x.team),mean:byes[w].has(x.team)?x.mean:0,sd:byes[w].has(x.team)?x.sd:0};const draws=GXEngine.samples(p,n,GXEngine.VERSION+':season:'+w,feed.calibration.same_team_rho);
 scores[w]=active.map(r=>{const b=GXEngine.partialLineup({...r,starters:[]},GXEngine.slots(league),p);if(b.ids.includes('0'))holes.push(name(r.roster_id)+' W'+w+': '+b.ids.map((id,i)=>id==='0'?GXEngine.slots(league)[i]:null).filter(Boolean).join(', '));return GXEngine.total(b.ids,draws,n);});await new Promise(r=>setTimeout(r,0));}
 if(Object.values(scores).some(a=>a.some(x=>!x))){$('gwOutlook').textContent='At least one roster cannot fill every starting slot during a future bye week. This fixed-roster scenario cannot finish legally without acquisitions; use Weak Spots and waivers. No championship probability is shown.';return;}
 const aliveCount=Object.fromEntries(Array.from({length:last-feed.week+1},(_,i)=>[feed.week+i,new Array(active.length).fill(0)]));for(let k=0;k<n;k++){let a=active.map((_,i)=>i),cumulative=active.map(r=>(r.settings?.fpts||0)+(r.settings?.fpts_decimal||0)/100);for(let w=feed.week;w<=last;w++){let low=Infinity,ties=[];for(const j of a){const x=Math.round(scores[w][j][k]*100);cumulative[j]+=x/100;if(x<low){low=x;ties=[j];}else if(x===low)ties.push(j);}let lo=GXEngine.tieLoser(active.map((r,i)=>({...r,settings:{...r.settings,fpts:cumulative[i],fpts_decimal:0}})),ties,w);if(lo==null)lo=ties[k%ties.length];a=a.filter(j=>j!==lo);for(const j of a)aliveCount[w][j]++;}}
 $('gwOutlook').innerHTML='<div class="gw-scroll">'+table(['Team',...Object.keys(aliveCount).map(w=>'W'+w)],active.map((r,i)=>'<tr><td>'+esc(name(r.roster_id))+'</td>'+Object.values(aliveCount).map(a=>'<td style="background:rgba(179,75,5,'+(a[i]/n*.22)+')">'+Math.round(100*a[i]/n)+'%</td>').join('')+'</tr>'))+'</div><p class="gw-note">'+n+' draws. Only this fixed-roster, repeated-strength scenario is modeled; actual future pickups can substantially change it. Empty positions score zero. Unresolved simulated ties are split across draws.</p>'+(holes.length?'<details><summary>Future empty-slot warnings ('+holes.length+')</summary><p>'+holes.map(esc).join('<br>')+'</p></details>':'');
 }catch(e){error(e);}finally{$('gwSeason').disabled=false;}}
$('gwLoad').onclick=()=>window.GW_INTEGRATED?openWeekly(true):load();$('gwFocus').onchange=()=>{if(window.GW_INTEGRATED&&league)window.dispatchEvent(new CustomEvent('gx-focus',{detail:{leagueId:league.league_id,rid:choice()}}));selectFocus();};$('gwCap').oninput=()=>{$('gwCapOut').textContent=$('gwCap').value+'%';};$('gwReplan').onclick=selectFocus;$('gwSeason').onclick=season;$('gwSaved').onchange=()=>{if($('gwSaved').value){$('gwLeague').value=$('gwSaved').value;load();}};
$('gwApplyActive').onclick=()=>{if(!league)return;saved[league.league_id]={...saved[league.league_id],excluded:Array.from(document.querySelectorAll('[data-active]')).filter(x=>!x.checked).map(x=>x.dataset.active)};save();load();};
$('gwLeague').onkeydown=e=>{if(e.key==='Enter')load();};document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));document.querySelectorAll('[data-view]').forEach(x=>x.hidden=x.dataset.view!==b.dataset.panel);});
const dashboardContext=window.DD_BOTCTX;const weeklyContext={label:'Last Dawg Standing',title:'Ask Toto about this weekly model',sys:'Use the current weekly model only. Do not call dd_guillotine_odds: it is a legacy historical-score tool and does not power this dashboard. It uses Sleeper weekly player statistics and league scoring, not historical team averages. Survival is a pregame simulation, not live scoring. Uncertainty fitted to possibly revised historical projections is descriptive, not validated. Same-team positive correlation is estimated; other correlations are omitted. FAAB planning ceilings are user-budget heuristics, not prices. Cost ranges summarize observed winning bids only; never claim known losing bids or independent market value. Suggestions do not write to Sleeper. Season outputs are fixed-roster scenarios. Focus selection is not verified ownership.',ctx:()=>JSON.stringify({league:league?.name,week:feed?.week,as_of:feed?.fetched_at,board:result?.rows?.map(r=>({...r,name:name(r.rid)})),focus:choice(),recommendation:focusResult?{current:focusResult.current,optimized:focusResult.optimized,plan:focusResult.plan}:null,limitations:feed?.calibration?.limitation})};
function clearWeekly(){
 ++generation;++focusGeneration;loadingLeague=null;result=null;focusResult=null;league=null;players=null;feed=null;
 if(worker){worker.terminate();worker=null;}for(const p of pending.values())p.reject(Error('League selection changed.'));pending.clear();
 for(const id of ['gwMetrics','gwBoard','gwChop','gwLineup','gwWaivers','gwWeak','gwBudgets','gwBids','gwOutlook','gwReceipts','gwMethod','gwHistory','gwActive'])$(id).textContent='';
 $('gwError').hidden=true;$('gwFocus').innerHTML='<option value="">Choose your team</option>';$('gwLoad').disabled=false;
 setStatus('Connect a league in League setup above to use weekly decisions.');
}
function openWeekly(refresh=false){
 if($('gw').hidden)return;window.DD_BOTCTX=weeklyContext;
 const g=window.__GX;if(!g?.leagueId){setStatus('Connect a league in League setup above to use weekly decisions.');return;}
 const id=String(g.leagueId),focus=g.me?.rid==null?'':String(g.me.rid);
 saved[id]={...saved[id],focus};$('gwLeague').value=id;
 if(loadingLeague===id)return;
 if(refresh||!result||String(league?.league_id)!==id){loadingLeague=id;load().finally(()=>{if(loadingLeague===id)loadingLeague=null;});return;}
 if(choice()!==focus){$('gwFocus').value=focus;selectFocus();}
}
if(window.GW_INTEGRATED){
 window.addEventListener('gx-sheet-change',e=>{if(e.detail.key==='weekly')openWeekly();else window.DD_BOTCTX=dashboardContext;});
 window.addEventListener('gx-loading',()=>{clearWeekly();});
 window.addEventListener('gx-ready',()=>{if(!$('gw').hidden)openWeekly();});
 clearWeekly();
 if(new URLSearchParams(location.search).get('view')==='weekly')document.querySelector('[data-gx-sheet="weekly"]').click();
}else{
 window.DD_BOTCTX=weeklyContext;
 $('gwLeague').value=new URLSearchParams(location.search).get('league')||saved.last||'1400972302392262656';load();
}
})();
