const test=require('node:test'),assert=require('node:assert/strict'),E=require('../guillotine-engine.js'),{capture,grade}=require('../tools/guillotine-receipts.cjs');
const league={league_id:'123456789',season:'2026',roster_positions:['QB','RB','RB','WR','WR','TE','FLEX','FLEX','BN'],scoring_settings:{pass_yd:.04,pass_td:4,pass_int:-1,rec:1,rec_yd:.1,rush_yd:.1,rush_td:6,fum_lost:-2},settings:{type:3,waiver_budget:1000}};
function player(id,position,mean,sd=0,extra={}){return {id,position,team:id,mean,sd,unavailable:false,started:false,...extra};}
function fixture(){let players={},rosters=[];for(let j=1;j<=3;j++){const ids=['QB','RB','RB','WR','WR','TE','WR','RB'].map((p,i)=>{const id=j+'-'+i;players[id]=player(id,p,10+j);return id;});rosters.push({roster_id:j,players:ids,starters:ids.slice(),settings:{draft_position:j,waiver_budget_used:0,fpts:j*10}});}return {players,rosters};}
test('league scoring includes PPR, turnovers and four-point passing touchdowns; zero is real',()=>{assert.equal(E.score({pass_yd:250,pass_td:2,pass_int:1,rec:3,rec_yd:40,fum_lost:1},league.scoring_settings),22);assert.equal(E.score({},league.scoring_settings),0);assert.equal(E.score(null,league.scoring_settings),null);assert.throws(()=>E.score({rec:NaN},league.scoring_settings));});
test('legal eight-starter lineups honor multi-position eligibility and never double-use players',()=>{const {players,rosters}=fixture(),r=rosters[0];players[r.players[3]].position='DB';players[r.players[3]].positions=['DB','WR'];const e=E.enumerate(r.players,E.slots(league),players);assert(e.candidates.length);for(const ids of e.candidates){assert.equal(new Set(ids).size,8);assert(ids.includes(r.players[3]));}});
test('started bench cannot enter and started starter cannot be moved; byes and Out do not start',()=>{const {players,rosters}=fixture(),r=rosters[0];players.b=player('b','QB',99,0,{started:true});r.players.push('b');players[r.starters[0]].started=true;const b=E.board(rosters,players,league);const o=E.optimize(r,players,league,b);assert.equal(o.best.ids[0],r.starters[0]);assert(!o.best.ids.includes('b'));players[r.starters[1]].unavailable=true;const o2=E.optimize(r,players,league,b);assert(!o2.best.ids.includes(r.starters[1]));assert(o2.incomplete);assert(o2.best.ids.includes('0'));});
test('board conserves one elimination, excludes chopped rosters, is deterministic and rejects missing starters',()=>{const {players,rosters}=fixture(),b=E.board(rosters,players,league,{n:200});assert.equal(b.rows.reduce((s,x)=>s+x.risk,0),1);assert.equal(b.rows.find(x=>x.rid===1).risk,1);assert.deepEqual(b.rows,E.board(rosters,players,league,{n:200}).rows);assert.equal(E.board(rosters,players,league,{excluded:['1'],n:200}).rows.length,2);delete players[rosters[0].starters[0]];assert.throws(()=>E.board(rosters,players,league),/Missing weekly projection/);});
test('Sleeper tie rules: better draft position chopped in W1; lower cumulative score afterward; unresolved tie is not invented',()=>{const r=[{settings:{draft_position:4,fpts:50}},{settings:{draft_position:2,fpts:80}},{settings:{draft_position:8,fpts:50}}];assert.equal(E.tieLoser(r,[0,1],1),1);assert.equal(E.tieLoser(r,[0,1],2),0);assert.equal(E.tieLoser(r,[0,2],2),null);assert.equal(E.tieLoser([{settings:{}} ,r[1]],[0,1],1),null);});
test('waiver upgrades compare optimized baseline, respect roster ownership and zero-dollar budgets, never fabricate auction evidence',()=>{const {players,rosters}=fixture(),r=rosters[0];players.new=player('new','QB',90);r.settings.waiver_budget_used=1000;const b=E.board(rosters,players,league,{n:100}),p=E.waiver(r,rosters,players,league,b,[],.15);assert.equal(p.left,0);assert.equal(p.cap,0);assert.equal(p.rows[0].id,'new');assert.equal(p.rows[0].delta,1);assert.equal(p.rows[0].suggested,null);assert.equal(p.rows[0].valueCap,0);assert.equal(p.rows[0].cost,null);assert(r.players.includes(p.rows[0].drop));assert(!p.rows[0].lineup.includes(p.rows[0].drop));});
test('future bye holes remain explicit zeros; partial lineup does not invent replacement players',()=>{const {players,rosters}=fixture();players[rosters[0].players[0]].unavailable=true;const p=E.partialLineup(rosters[0],E.slots(league),players);assert.equal(p.ids[0],'0');assert.equal(p.ids.filter(x=>x!=='0').length,7);assert.equal(p.mean,77);});
function receiptFixture(){const now=Date.parse('2026-09-09T14:15:00Z'),l={...league,roster_positions:['QB'],scoring_settings:{pass_td:4}},feed={season:2026,week:1,fetched_at:new Date(now).toISOString(),calibration:{scoring:{pass_td:4},buckets:{QB:{sd:2,n:100}},same_team_rho:0},players:[{id:'a',position:'QB',team:'A',opponent:'B',kickoff:'2026-09-10T00:20:00Z',stats:{pass_td:3}},{id:'b',position:'QB',team:'B',opponent:'A',kickoff:'2026-09-10T00:20:00Z',stats:{pass_td:2}}]},rosters=[{roster_id:1,players:['a'],starters:['a'],settings:{draft_position:1}},{roster_id:2,players:['b'],starters:['b'],settings:{draft_position:2}}],games=[{season:2026,week:1,season_type:'REG',kickoff_at:'2026-09-10T00:20:00Z'}];return {now,league:l,feed,rosters,games};}
test('prospective capture only inside pregame gate; stale data and unknown scoring refuse capture',()=>{const f=receiptFixture(),r=capture(f);assert.equal(r.status,'pending');assert.equal(r.rows.length,2);assert(!JSON.stringify(r).includes('starters'));assert.equal(capture({...f,now:Date.parse(r.kickoff_at)}),null);assert.equal(capture({...f,now:f.now-86400000}),null);assert.throws(()=>capture({...f,feed:{...f.feed,fetched_at:'2026-09-01'}}),/Stale/);assert.throws(()=>E.makePlayers(f.feed,{...f.league,scoring_settings:{pass_td:6}}),/Scoring changed/);});
test('missing projection differs from real zero, and injury zeros do not inherit variance',()=>{const f=receiptFixture();f.feed.players[0].has_projection=false;f.feed.players[1].injury='Out';const p=E.makePlayers(f.feed,f.league,f.now);assert.equal(p.a,undefined);assert.equal(p.b.mean,0);assert.equal(p.b.sd,0);});
test('grading waits for completed week, accepts zero and negative points, is immutable and defers unresolved ties',()=>{const f=receiptFixture(),r=capture(f),now=f.now+7*86400000,m=[{roster_id:1,points:0},{roster_id:2,points:4}];assert.equal(grade(r,m,{season:2026,display_week:1},now).status,'pending');const g=grade(r,m,{season:2026,display_week:2},now);assert.equal(g.chopped_rid,1);assert.equal(g.status,'graded');assert.equal(g.brier,g.rows.reduce((s,x)=>s+(x.risk-(x.rid===1?1:0))**2,0));assert.deepEqual(grade(g,[],{season:2026,display_week:2},now),g);assert.equal(grade(r,[{roster_id:1,points:-1},{roster_id:2,points:0}],{season:2026,display_week:2},now).chopped_rid,1);const tied={...r,week:2,rows:r.rows.map(x=>({...x,prior_season_points:0}))};assert.equal(grade(tied,[{roster_id:1,points:0},{roster_id:2,points:0}],{season:2026,display_week:3},now).status,'waiting-tiebreak');});
test('league switch selects its own scoring calibration and rejects unsupported scoring',()=>{const f=receiptFixture();f.feed.calibrations={case:{...f.feed.calibration,scoring:{pass_td:6},buckets:{QB:{sd:5,n:90}}}};const other={...f.league,league_id:'case',scoring_settings:{pass_td:6}};const p=E.makePlayers(f.feed,other,f.now);assert.equal(p.a.mean,18);assert.equal(p.a.sd,5);assert.equal(E.makePlayers(f.feed,f.league,f.now).a.mean,12);assert.throws(()=>E.makePlayers(f.feed,{...other,scoring_settings:{pass_td:7}}),/not yet supported/);});

const pageSource=require('node:fs').readFileSync(require('node:path').join(__dirname,'../guillotine.html'),'utf8');
test('season projection caches are separate and a failed fetch can recover',async()=>{
 const start=pageSource.indexOf('  var PROJ_P ='),end=pageSource.indexOf('  /* Byes come',start);let calls=[],fail=true;
 const fetch=async url=>{calls.push(url);if(fail){fail=false;throw Error('temporary');}return {ok:true,json:async()=>[{season:url.match(/nfl\/(\d+)/)[1]}]};};
 const proj=new Function('fetch',pageSource.slice(start,end)+';return projRows;')(fetch);
 await assert.rejects(proj(2026),/temporary/);assert.equal((await proj(2026))[0].season,'2026');assert.equal((await proj(2025))[0].season,'2025');await proj(2026);assert.equal(calls.length,3);
});
test('original waiver plan respects a zero-dollar remaining budget',async()=>{
 const start=pageSource.indexOf('  var PLAN_STEPS ='),end=pageSource.indexOf('  async function weakSpots',start);
 const players={a:{id:'a',pg:10,name:'Starter'},b:{id:'b',pg:20,name:'Upgrade'}};
 const shape=ps=>({total:Math.max(...ps.map(p=>p.pg))});
 const plan=new Function('projRows','playerMap','lineupSlots','lineupShape','lineupGain',pageSource.slice(start,end)+';return waiverPlan;')(async()=>[],()=>players,()=>({}),shape,(ps,c,sl,base)=>shape(ps.concat(c)).total-base);
 const p=await plan({season:2026,settings:{waiver_budget:1000}},[{roster_id:1,players:['a'],settings:{waiver_budget_used:1000}}],1,0);
 assert.equal(p.left,0);assert.equal(p.steps[0].lo,0);assert.equal(p.steps[0].hi,0);
});
test('local votes close at actual first kickoff, including a Wednesday opener',()=>{
 const start=pageSource.indexOf('  function locked(){'),end=pageSource.indexOf('\n',start),source=pageSource.slice(start,end);
 let now=Date.parse('2026-09-10T00:19:59Z');const win={GW_INTEGRATED:true,GX_VOTE_DEADLINE:Date.parse('2026-09-10T00:20:00Z')};
 const locked=new Function('window','Date',source+';return locked;')(win,{now:()=>now});
 assert.equal(locked(),false);now+=1000;assert.equal(locked(),true);win.GX_VOTE_DEADLINE=null;assert.equal(locked(),true);
});
