"""
Apply the mobile audit to teamdraft.html IN PLACE — Stage TD-MOBILE.

⚠️ WHY THIS IS A PATCH AND NOT A REBUILD.

teamdraft.html is generated by work/build_teamdraft.py, so the obvious move is to
edit the builder and re-stamp the page. That would have destroyed 330 lines of
somebody else's work.

The Toto page-reader stages (#17, #18, #19) edited teamdraft.html DIRECTLY, through
their own sitewide patch scripts, and never touched this page's builder. Re-running
build_teamdraft.py regenerates the file from arena.html plus the builder's own MAIN
and SCRIPT strings — every Toto hook in it would simply vanish, with no conflict and
no warning. That is AGENTS.md rule 1 playing out inside a single file instead of
across a stale checkout.

So the edits land twice, on purpose:

  · here, against the shipped page, preserving whatever else is in it
  · in work/build_teamdraft.py, so a future full rebuild still carries them

Both are already true when this script runs; it exists to make the first one
reproducible and to fail loudly if the page has drifted underneath it.

Run:  cd work && python3 patch-teamdraft-mobile.py && python3 stamp-sw-version.py
"""
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
PAGE = REPO / "teamdraft.html"

html = PAGE.read_text(encoding="utf-8")


def sub1(old, new, what):
    global html
    n = html.count(old)
    assert n == 1, f"anchor {what!r} appears {n} times in teamdraft.html, expected 1"
    html = html.replace(old, new, 1)


# --------------------------------------------------------------- 1 · the tabs ----
# Four multi-word labels wrapped onto two rows at 390px with "Rules & method"
# stranded alone underneath — the tab a first-time reader most needs, in the place
# they are least likely to look.
sub1('''sheets:[{id:"pool",  label:"The pool",       panel:"#sheetPool"},
              {id:"team",  label:"One team",       panel:"#sheetTeam"},
              {id:"diag",  label:"Diagnostics",    panel:"#sheetDiag", hint:"what drifts"},
              {id:"rules", label:"Rules & method", panel:"#sheetRules"}],''',
     '''sheets:[{id:"pool",  label:"Pool",        panel:"#sheetPool"},
              {id:"team",  label:"Roster",      panel:"#sheetTeam"},
              {id:"diag",  label:"Diagnostics", panel:"#sheetDiag"},
              {id:"rules", label:"Rules",       panel:"#sheetRules", hint:"start here"}],''',
     "sheet labels")

# Rules is tinted so it reads as an invitation rather than the quietest word in the row.
sub1('''[role=tabpanel][hidden]{display:none}''',
     '''[role=tabpanel][hidden]{display:none}
#tab-rules{border:1px solid color-mix(in srgb,var(--accent) 42%,transparent);
  border-bottom-width:2px;border-radius:8px 8px 0 0;
  background:color-mix(in srgb,var(--accent) 9%,transparent);color:var(--ink-1)}
#tab-rules:hover{background:color-mix(in srgb,var(--accent) 16%,transparent)}
#tab-rules.on{background:color-mix(in srgb,var(--accent) 14%,transparent)}
#tab-rules .sheet-hint{color:var(--accent);
  background:color-mix(in srgb,var(--accent) 18%,transparent)}''',
     "rules tab tint")

# ------------------------------------------------------- 2 · the sticky header ----
# Measured at 390x844: the wrapped rail alone was 206px, 24% of the screen, held
# there permanently once you scrolled.
sub1('''.td-rail{position:sticky;top:0;z-index:40;margin:0 0 18px;padding:11px 0 10px;
  background:var(--page);border-bottom:1px solid var(--grid)}''',
     '''.td-sticky{position:sticky;top:0;z-index:40;background:var(--page);margin-bottom:18px;
  box-shadow:0 6px 14px -12px rgba(0,0,0,.55)}
.td-sticky .sheetbar{margin-bottom:0;padding-top:2px}
.td-rail{padding:11px 0 10px;border-bottom:1px solid var(--grid)}
.td-rail[hidden]{display:none}''',
     "sticky header css")

sub1('''<div id="sheets"></div>
  <div class="td-rail">
    <div class="td-rail-in" id="tdRail" role="group" aria-label="Choose a drafter or a team"></div>
  </div>''',
     '''<div class="td-sticky">
    <div id="sheets"></div>
    <div class="td-rail">
      <div class="td-rail-in" id="tdRail" role="group" aria-label="Choose a drafter or a team"></div>
    </div>
  </div>''',
     "sticky wrapper")

sub1('''@media (max-width:560px){
  .td-matrix{--cell:11px;''',
     '''@media (max-width:700px){
  .td-rail-in{flex-wrap:nowrap;overflow-x:auto;overflow-y:hidden;
    scrollbar-width:none;-webkit-overflow-scrolling:touch;
    padding-bottom:2px;scroll-padding-left:8px}
  .td-rail-in::-webkit-scrollbar{display:none}
  .td-rail-in > *{flex:0 0 auto}
  .td-rail-lab{display:none}
  .td-pick{max-width:150px}
}
.p-section{scroll-margin-top:74px}

@media (max-width:560px){
  .td-matrix{--cell:11px;''',
     "mobile rail")

# ------------------------------------------------- 3 · the rail where it matters ----
sub1('''      onShow(id){''',
     '''      onShow(id){
        const rail = document.querySelector(".td-rail");
        if(rail) rail.hidden = (id === "diag" || id === "rules");''',
     "rail visibility")

# --------------------------------------------------- 4 · the Roster sheet default ----
# It opened on the top of the expected-wins ladder, which is an NFL team. This sheet
# is somebody's four teams; opening it on the Rams made the page read as though it
# were about clubs rather than the eight people playing.
sub1('''        if(id === "team" && selEmpty()){
          autoPick = Object.keys(D.teams).sort((a,b)=>D.teams[b].ew - D.teams[a].ew)[0];
          sel.t.add(autoPick);
        }''',
     '''        if(id === "team" && selEmpty()){
          const W = D.wins_tracker || {};
          const played = D.draft_order.some(n => (W[n]?.total || 0) > 0);
          autoPick = played
            ? [...D.draft_order].sort((a,b)=>(W[b].total||0)-(W[a].total||0))[0]
            : D.draft_order[0];
          sel.d.add(autoPick);
        }''',
     "roster default")

# autoPick can now live in either bag, so clearing it has to check both
sub1('''if(autoPick && autoPick !== id){ sel.t.delete(autoPick); }''',
     '''if(autoPick && autoPick !== id){ sel.d.delete(autoPick); sel.t.delete(autoPick); }''',
     "autoPick clear (chip)")
sub1('''if(autoPick && autoPick !== v) sel.t.delete(autoPick);''',
     '''if(autoPick && autoPick !== v){ sel.d.delete(autoPick); sel.t.delete(autoPick); }''',
     "autoPick clear (dropdown)")

sub1('''<h2>Pick a team</h2><p class="sub">Use the rail above, or click any
        bar on the ladder. This sheet is the one-team view — the week-by-week strip, the season
        curve and the full schedule.</p>''',
     '''<h2>Pick a drafter</h2><p class="sub">Tap a name above to see their
        four teams week by week, how their season lands, and every game. Tap a second name to lay
        two of them over each other, or add a single NFL team from the menu.</p>''',
     "empty-state copy")

# ------------------------------------------------------------------------ guards ----
assert html.count('class="td-sticky"') == 1
assert html.count("#tab-rules{") == 1
assert html.count('label:"Roster"') == 1 and 'label:"One team"' not in html
assert "sel.d.add(autoPick)" in html and "sel.t.add(autoPick)" not in html
# ⚠️ The whole reason this is a patch: prove the other session's work is still here.
assert "toto" in html.lower(), "the Toto page-reader hooks were lost"
assert "\r" not in html, "CRLF crept in; this repo is all-LF"

PAGE.write_text(html, encoding="utf-8")
print(f"patched teamdraft.html: {len(html.encode('utf-8'))} bytes, Toto hooks intact")
