"""
patch-showdown-validator.py — add the Showdown Validator sheet to dfs.html.

Repo convention (AGENTS.md rule 2): content-marker string replace with
`assert s.count(old) == 1`. There is no page build system; dfs.html IS the source, and
the DFS modules are pasted into it under a `source:` comment the way dfs-engine.js and
dfs-validators.js already are. This script does that paste from dfs/showdown/*.js so the
page and the headless tests never drift.

Re-runnable: it removes its own previously injected blocks first, so editing a module and
re-running restamps rather than duplicating.

Run:  cd work && python3 patch-showdown-validator.py
"""
import pathlib, re

REPO = pathlib.Path(__file__).resolve().parent.parent
PAGE = REPO / "dfs.html"
SRC = REPO / "dfs" / "showdown"

s = PAGE.read_text(encoding="utf-8")

BEGIN = "/* ==== BEGIN showdown validator (generated by work/patch-showdown-validator.py) ==== */"
END = "/* ==== END showdown validator ==== */"
UI_BEGIN = "<!-- ==== BEGIN showdown validator UI ==== -->"
UI_END = "<!-- ==== END showdown validator UI ==== -->"
CTRL_BEGIN = "/* ==== BEGIN showdown validator ui ==== */"
CTRL_END = "/* ==== END showdown validator ui ==== */"
CSS_BEGIN = "/* ==== BEGIN showdown validator css ==== */"
CSS_END = "/* ==== END showdown validator css ==== */"

def strip_block(text, begin, end):
    """Remove a previously injected block and EXACTLY the padding it was inserted with:
    one leading newline, the block, two trailing newlines. Every insertion below emits
    that same shape, which is what makes a second run reproduce the first byte for byte.
    A looser strip leaves a stray newline behind and the file grows on every run."""
    while begin in text:
        i = text.index(begin)
        j = text.index(end, i) + len(end)
        if text[j:j + 2] == "\n\n":
            j += 2
        if i > 0 and text[i - 1] == "\n":
            i -= 1
        text = text[:i] + text[j:]
    return text

s = strip_block(s, BEGIN, END)
s = strip_block(s, UI_BEGIN, UI_END)
s = strip_block(s, CTRL_BEGIN, CTRL_END)
s = strip_block(s, CSS_BEGIN, CSS_END)

def once(hay, needle, what):
    n = hay.count(needle)
    assert n == 1, f"marker {what!r} appears {n} times in dfs.html, expected 1"

# ---------------------------------------------------------------- 1. tab button
# The three edits below sit outside the removable blocks, so each is guarded and skipped
# on a re-run. That is what keeps the script byte-stable on a second pass.
if 'data-s="showdown"' not in s:
    TAB_ANCHOR = '    <button data-s="method">Method<span class="kbd">8</span></button>\n'
    once(s, TAB_ANCHOR, "method tab")
    s = s.replace(
        TAB_ANCHOR,
        '    <button data-s="showdown">Showdown<span class="kbd">8</span></button>\n'
        '    <button data-s="method">Method<span class="kbd">9</span></button>\n',
        1)

# ---------------------------------------------------------------- 2. sheet registry
SHEETS_OLD = 'const SHEETS = ["slate", "solver", "sim", "exposure", "bankroll", "screener", "standings", "method"];'
if SHEETS_OLD in s:
    once(s, SHEETS_OLD, "SHEETS list")
    s = s.replace(
        SHEETS_OLD,
        'const SHEETS = ["slate", "solver", "sim", "exposure", "bankroll", "screener", "standings", "showdown", "method"];',
        1)
assert '"standings", "showdown", "method"' in s, "SHEETS never gained the showdown sheet"

RENDER_ANCHOR = '  if (name === "method") renderMethod();'
if 'if (name === "showdown") renderShowdown();' not in s:
    once(s, RENDER_ANCHOR, "sheet render hook")
    s = s.replace(RENDER_ANCHOR, '  if (name === "showdown") renderShowdown();\n' + RENDER_ANCHOR, 1)

# ---------------------------------------------------------------- 3. engine modules
MODULES = ["construction.js", "rules.js", "dupeRisk.js", "validator.js"]
parts = [BEGIN,
         "/* Pasted from dfs/showdown/ by work/patch-showdown-validator.py — do not hand-edit",
         "   this block. Edit the module and re-run the script. The same source runs headless",
         "   under `node --test tests/showdown-validator.test.js`. */"]
for m in MODULES:
    body = (SRC / m).read_text(encoding="utf-8")
    # The browser copy resolves its dependencies off the globals the earlier modules set,
    # so the CommonJS require() paths must not be evaluated here.
    body = body.replace('typeof require === "function" ? require("./construction.js") : null', "null")
    body = body.replace('req ? req("./construction.js") : null', "null")
    body = body.replace('req ? req("./rules.js") : null', "null")
    body = body.replace('req ? req("./dupeRisk.js") : null', "null")
    parts.append(f"/* ---- source: dfs/showdown/{m} ---- */")
    parts.append(body.rstrip())
parts.append(END)
BLOCK = "\n".join(parts)

ENGINE_ANCHOR = "/* ---------------------------------------------------------------- sheets */"
once(s, ENGINE_ANCHOR, "sheets section")
s = s.replace(ENGINE_ANCHOR, "\n" + BLOCK + "\n\n" + ENGINE_ANCHOR, 1)

# ---------------------------------------------------------------- 4. the sheet markup
UI = UI_BEGIN + r"""
<section class="sheet" id="sh-showdown" hidden>
  <div class="card">
    <h3>8 · Showdown validator <span class="rt" id="sdState"></span></h3>
    <p class="sub">Judges how a DK Showdown lineup is <em>built</em>, and how likely it is to be duplicated.
    It does not build lineups and it does not tell you a lineup is good. Load the player pool on the
    <a href="#slate" data-goto="slate">Slate</a> sheet first — this sheet reads that pool.</p>
    <div class="sdgrid">
      <label class="fld"><span>Favourite</span><select class="fi" id="sdFav"></select></label>
      <label class="fld"><span>Spread <span class="hint">— favourite's number</span></span>
        <input class="fi" id="sdSpread" type="number" step="0.5" value="-3.5" inputmode="decimal"></label>
      <label class="fld"><span>Total</span><input class="fi" id="sdTotal" type="number" step="0.5" value="44.5" inputmode="decimal"></label>
    </div>
    <p class="note" id="sdPoolMsg"></p>
  </div>

  <div class="card">
    <h3>The lineup</h3>
    <div class="sdmeter" id="sdMeter"><b id="sdSal">$0</b><span id="sdSalNote">of $50,000</span><i id="sdBar"></i></div>
    <div class="sdslots" id="sdSlots"></div>
    <div class="btnrow">
      <button class="btn sm" id="sdCheck">Validate</button>
      <button class="btn sm ghost" id="sdAdd">Add to portfolio</button>
      <button class="btn sm ghost" id="sdClear">Clear</button>
    </div>
    <p class="note" id="sdMsg"></p>
  </div>

  <div class="card" id="sdResultCard" hidden>
    <h3>Result <span class="rt" id="sdBadge"></span></h3>
    <div id="sdResult"></div>
  </div>

  <div class="card">
    <h3>Portfolio <span class="rt" id="sdCount">0 lineups</span></h3>
    <p class="sub">Paste DK upload rows (<span class="mono">CPT,FLEX,FLEX,FLEX,FLEX,FLEX</span> of player names or DK ids),
    one lineup per line, or add them from the builder above.</p>
    <textarea class="fi mono" id="sdPaste" rows="4" spellcheck="false" placeholder="Josh Allen,Stefon Diggs,..."></textarea>
    <div class="btnrow">
      <button class="btn sm" id="sdImport">Import rows</button>
      <button class="btn sm ghost" id="sdValidateAll">Validate all</button>
      <button class="btn sm ghost" id="sdExport">Copy DK upload CSV</button>
      <button class="btn sm ghost" id="sdWipe">Empty it</button>
    </div>
    <p class="note" id="sdPortMsg"></p>
    <div id="sdPortfolio"></div>
  </div>
</section>
""" + UI_END

SHEET_ANCHOR = '<!-- ======================================================= SLATE -->'
once(s, SHEET_ANCHOR, "slate sheet comment")
s = s.replace(SHEET_ANCHOR, "\n" + UI + "\n\n" + SHEET_ANCHOR, 1)

# ---------------------------------------------------------------- 5. css
CSS = CSS_BEGIN + r"""
/* Mobile first: one column, and nothing that can push the page sideways at 380px. */
.sdgrid{display:grid;grid-template-columns:1fr;gap:0 14px}
.sdslots{display:grid;grid-template-columns:1fr;gap:8px;margin:12px 0 14px}
.sdslot{display:grid;grid-template-columns:44px 1fr;gap:8px;align-items:center}
.sdslot .tag{font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;
  color:var(--ink-3);text-align:right}
.sdslot .tag.cpt{color:var(--accent)}
.sdmeter{position:sticky;top:0;z-index:5;background:var(--surface-1);border:1px solid var(--border);
  border-radius:11px;padding:9px 12px;display:flex;align-items:baseline;gap:8px;flex-wrap:wrap;
  margin:0 0 12px}
.sdmeter b{font-size:17px;font-weight:800;font-variant-numeric:tabular-nums}
.sdmeter span{font-size:12px;color:var(--ink-3)}
.sdmeter i{display:block;flex:1 0 100%;height:4px;border-radius:3px;background:var(--grid);
  overflow:hidden;position:relative}
.sdmeter i::after{content:"";position:absolute;inset:0 auto 0 0;width:var(--pct,0%);
  background:var(--accent);border-radius:3px}
.sdmeter.over b{color:var(--bad)}
.sdmeter.over i::after{background:var(--bad)}
.sdchips{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 12px}
.sdchip{font-size:11px;font-weight:800;letter-spacing:.04em;padding:4px 9px;border-radius:999px;
  border:1px solid var(--border);color:var(--ink-2);background:var(--page)}
.sdchip.hard{border-color:color-mix(in srgb,var(--bad) 55%,transparent);color:var(--bad)}
.sdchip.soft{border-color:color-mix(in srgb,var(--warn) 55%,transparent);color:var(--warn)}
.sdchip.info{border-color:color-mix(in srgb,var(--accent) 45%,transparent);color:var(--accent)}
.sdchip.good{border-color:color-mix(in srgb,var(--good) 55%,transparent);color:var(--good)}
.sdflag{border-left:3px solid var(--border);padding:7px 0 7px 11px;margin:0 0 9px}
.sdflag.hard{border-left-color:var(--bad)}
.sdflag.soft{border-left-color:var(--warn)}
.sdflag.info{border-left-color:var(--accent)}
.sdflag h5{margin:0 0 3px;font-size:13px;font-weight:750;color:var(--ink-1);line-height:1.45}
.sdflag p{margin:0;font-size:12.5px;color:var(--ink-3);line-height:1.55}
.sdflag .rid{font-size:10px;font-weight:800;color:var(--ink-3);opacity:.7;margin-right:6px}
.sdgroup{margin:0 0 4px}
.sdgroup>summary{cursor:pointer;font-size:11px;font-weight:800;letter-spacing:.08em;
  text-transform:uppercase;color:var(--ink-3);padding:6px 0;list-style:none}
.sdgroup>summary::-webkit-details-marker{display:none}
.sdgroup>summary::before{content:"▸ ";opacity:.6}
.sdgroup[open]>summary::before{content:"▾ "}
.sdrow{display:flex;gap:8px;align-items:baseline;justify-content:space-between;
  padding:8px 0;border-top:1px solid var(--grid);font-size:13px;flex-wrap:wrap}
.sdrow .nm{font-weight:700}
.sdbar{display:grid;grid-template-columns:minmax(90px,1fr) 2fr auto;gap:8px;align-items:center;
  font-size:12.5px;padding:4px 0}
.sdbar i{display:block;height:6px;border-radius:3px;background:var(--grid);position:relative}
.sdbar i::after{content:"";position:absolute;inset:0 auto 0 0;width:var(--pct,0%);
  background:var(--accent);border-radius:3px}
.sdscroll{overflow-x:auto}
@media(min-width:720px){
  .sdgrid{grid-template-columns:repeat(3,1fr)}
  .sdslots{grid-template-columns:1fr 1fr}
}
""" + CSS_END

# The inlined site.css has no newline before its close tag, so anchor on the tag itself.
# dfs.html gained a SECOND <style> block when main landed the Lineup Lab work, so this
# deliberately does not assert uniqueness — it targets the FIRST close tag, which is the
# inlined site.css where this block already lives. `.replace(..., 1)` hits that one.
CSS_ANCHOR = "</style>"
assert CSS_ANCHOR in s, "no </style> in dfs.html to anchor the showdown CSS on"
s = s.replace(CSS_ANCHOR, "\n" + CSS + "\n\n" + CSS_ANCHOR, 1)

# ---------------------------------------------------------------- 6. controller
CTRL = CTRL_BEGIN + r"""
/* ---------------------------------------------------------------- showdown validator ui */
/* Adapts the page's pool (work/dfs-slate-ingest.js shape: sal / own on a 0-100 scale) to
   the validator's Player contract (salary / own as a 0-1 fraction). The scale conversion
   lives here, at the boundary, and nowhere else. */
const SD = { lineup: { cpt: "", flex: ["", "", "", "", ""] }, portfolio: [], lastSlate: null };

function sdPool() {
  return (S.players || [])
    .filter(p => p && p.sal > 0)
    .map(p => ({
      id: p.dkId || (p.name + "|" + p.team),
      name: p.name,
      team: p.team,
      pos: p.pos,
      salary: p.sal,
      proj: p.proj != null ? p.proj : 0,
      own: p.own != null ? p.own / 100 : undefined,
      cptOwn: p.cptOwn != null ? p.cptOwn / 100 : undefined
    }));
}

function sdSlate() {
  const players = sdPool();
  const teams = [];
  players.forEach(p => { if (p.team && teams.indexOf(p.team) < 0) teams.push(p.team); });
  const fav = $("sdFav").value || teams[0] || "";
  return {
    id: "sd-" + teams.join("-") + "-" + fav + "-" + $("sdSpread").value,
    home: teams[0] || "", away: teams[1] || "",
    favorite: fav,
    spread: parseFloat($("sdSpread").value),
    total: parseFloat($("sdTotal").value),
    players: players,
    favKickerFieldUsage51: null
  };
}

function sdFmt(n, dp) { return n == null ? "—" : (+n).toFixed(dp == null ? 2 : dp); }
function sdPct(n) { return n == null ? "—" : Math.round(n * 100) + "%"; }
function sdEsc(t) { return String(t == null ? "" : t).replace(/[<>&]/g, c => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" }[c])); }

function renderShowdown() {
  const players = sdPool();
  const teams = [];
  players.forEach(p => { if (p.team && teams.indexOf(p.team) < 0) teams.push(p.team); });
  const sel = $("sdFav"), keep = sel.value;
  sel.innerHTML = teams.map(t => `<option value="${sdEsc(t)}">${sdEsc(t)}</option>`).join("");
  if (teams.indexOf(keep) >= 0) sel.value = keep;

  const priced = players.filter(p => p.proj > 0).length;
  const owned = players.filter(p => p.own != null).length;
  $("sdState").textContent = players.length ? players.length + " players" : "no pool";
  $("sdPoolMsg").textContent = !players.length
    ? "No pool loaded. Upload a DK Showdown salary file on the Slate sheet."
    : teams.length !== 2
      ? "This pool has " + teams.length + " team(s). Showdown needs exactly two — load a single-game file."
      : priced === 0
        ? "Salaries loaded, no projections yet. The relative-projection and duplication readings need them."
        : owned === 0
          ? "Projections loaded, no ownership. Duplication rules will be skipped and said so."
          : "Pool ready: " + priced + " projected, " + owned + " with ownership.";

  sdRenderSlots(players);
  sdMeter();
  sdRenderPortfolio();
}

function sdRenderSlots(players) {
  const opts = seed => ['<option value="">—</option>'].concat(
    players.slice().sort((a, b) => b.salary - a.salary || a.name.localeCompare(b.name))
      .map(p => `<option value="${sdEsc(p.id)}"${p.id === seed ? " selected" : ""}>${sdEsc(p.name)} · ${sdEsc(p.team)} ${sdEsc(p.pos)} · $${p.salary.toLocaleString("en-US")}</option>`)
  ).join("");
  const rows = [`<div class="sdslot"><span class="tag cpt">CPT</span><select class="fi" data-sd="cpt">${opts(SD.lineup.cpt)}</select></div>`];
  for (let i = 0; i < 5; i++) {
    rows.push(`<div class="sdslot"><span class="tag">FLEX</span><select class="fi" data-sd="${i}">${opts(SD.lineup.flex[i])}</select></div>`);
  }
  $("sdSlots").innerHTML = rows.join("");
}

function sdMeter() {
  const by = {}; sdPool().forEach(p => by[p.id] = p);
  let total = 0, filled = 0;
  if (SD.lineup.cpt && by[SD.lineup.cpt]) { total += by[SD.lineup.cpt].salary * 1.5; filled++; }
  SD.lineup.flex.forEach(id => { if (id && by[id]) { total += by[id].salary; filled++; } });
  const m = $("sdMeter");
  $("sdSal").textContent = "$" + Math.round(total).toLocaleString("en-US");
  $("sdSalNote").textContent = "of $50,000 · " + filled + "/6 filled" +
    (filled === 6 ? " · $" + Math.round(50000 - total).toLocaleString("en-US") + " left" : "");
  m.classList.toggle("over", total > 50000);
  m.style.setProperty("--pct", Math.min(100, (total / 50000) * 100) + "%");
}

function sdFlagHtml(f) {
  return `<div class="sdflag ${f.severity}"><h5><span class="rid">${sdEsc(f.rule)}</span>${sdEsc(f.message)}</h5>` +
         `<p>${sdEsc(f.fix)}</p></div>`;
}

function sdResultHtml(r) {
  if (!r.valid) {
    return `<div class="sdchips"><span class="sdchip hard">Not a legal entry</span></div>` +
      r.errors.map(e => `<div class="sdflag hard"><h5>${sdEsc(e.message)}</h5></div>`).join("") +
      `<p class="note">Construction is not graded on a lineup that cannot be entered.</p>`;
  }
  const tierClass = { severe: "hard", elevated: "soft", moderate: "info", low: "good", unknown: "" }[r.dupeRisk.tier] || "";
  const chips = [
    `<span class="sdchip">${sdEsc(r.build.type)} ${sdEsc(r.build.heavySide || "even")}</span>`,
    `<span class="sdchip">CPT ${sdEsc(r.cpt.name)} · ${sdEsc(r.cpt.pos)} · ${r.cpt.side === "fav" ? "favourite" : "dog"}</span>`,
    `<span class="sdchip ${tierClass}">dupe: ${sdEsc(r.dupeRisk.tier)}</span>`,
    r.score.hard ? `<span class="sdchip hard">${r.score.hard} hard</span>` : "",
    r.score.soft ? `<span class="sdchip soft">${r.score.soft} soft</span>` : "",
    r.score.info ? `<span class="sdchip info">${r.score.info} info</span>` : ""
  ].join("");

  const stack = r.stacks;
  const facts = [
    ["Salary", "$" + Math.round(r.salary).toLocaleString("en-US")],
    ["Projection", sdFmt(r.proj, 1)],
    ["Vs. max-projection", r.ownership.relativeProj == null ? "—" : sdPct(r.ownership.relativeProj)],
    ["Cumulative ownership", r.ownership.cumulative == null ? "—" : sdPct(r.ownership.cumulative)],
    ["Captain's own catchers", String(stack.sameTeamWRTE)],
    ["Bring-back catchers", String(stack.oppWRTE)]
  ].map(([k, v]) => `<div class="sdrow"><span>${k}</span><b class="nm">${sdEsc(v)}</b></div>`).join("");

  const groups = ["hard", "soft", "info"].map(sev => {
    const fs = r.flags.filter(f => f.severity === sev);
    if (!fs.length) return "";
    const label = { hard: "Likely errors", soft: "Deviates from what wins", info: "Context" }[sev];
    return `<details class="sdgroup"${sev === "info" ? "" : " open"}><summary>${label} · ${fs.length}</summary>` +
           fs.map(sdFlagHtml).join("") + `</details>`;
  }).join("");

  const notes = r.notes.length
    ? `<details class="sdgroup"><summary>Not checked · ${r.notes.length}</summary>` +
      r.notes.map(n => `<p class="note">${sdEsc(n.message)}</p>`).join("") + `</details>`
    : "";

  return `<div class="sdchips">${chips}</div>` +
    (r.flags.length ? groups : `<p class="note">Nothing flagged. That is not the same as a good lineup.</p>`) +
    `<div style="margin-top:10px">${facts}</div>` +
    `<p class="note" style="margin-top:10px">${sdEsc(r.dupeRisk.note)}</p>` + notes;
}

function sdValidateCurrent() {
  const lineup = { id: "builder", cpt: SD.lineup.cpt, flex: SD.lineup.flex.slice() };
  if (!lineup.cpt || lineup.flex.some(x => !x)) {
    $("sdMsg").textContent = "Fill all six slots first.";
    $("sdMsg").className = "note warn";
    return null;
  }
  const r = DDSDValidator.validateLineup(lineup, sdSlate());
  $("sdMsg").textContent = "";
  $("sdResultCard").hidden = false;
  $("sdBadge").textContent = r.valid ? (r.score.hard ? r.score.hard + " hard" : "clean") : "illegal";
  $("sdResult").innerHTML = sdResultHtml(r);
  return r;
}

function sdRenderPortfolio() {
  $("sdCount").textContent = SD.portfolio.length + " lineup" + (SD.portfolio.length === 1 ? "" : "s");
  const host = $("sdPortfolio");
  if (!SD.portfolio.length) { host.innerHTML = ""; return; }
  const p = DDSDValidator.validatePortfolio(SD.portfolio, sdSlate());
  const by = {}; sdPool().forEach(x => by[x.id] = x);

  const rows = p.lineups.map((r, i) => {
    const l = SD.portfolio[i];
    const nm = [l.cpt].concat(l.flex).map(id => (by[id] || {}).name || id).join(", ");
    const badge = !r.valid ? `<span class="sdchip hard">illegal</span>`
      : `<span class="sdchip ${r.score.hard ? "hard" : r.score.soft ? "soft" : "good"}">${r.score.hard}H ${r.score.soft}S ${r.score.info}I</span>`;
    return `<div class="sdrow"><span class="nm">${i + 1}. ${sdEsc(nm)}</span>${badge}</div>`;
  }).join("");

  const cptBars = p.cptExposure.map(e =>
    `<div class="sdbar"><span>${sdEsc(e.name)}</span><i style="--pct:${Math.round(e.exposure * 100)}%"></i><b>${sdPct(e.exposure)}</b></div>`
  ).join("");

  const mix = Object.keys(p.buildMix).sort().map(k =>
    `<div class="sdbar"><span>${sdEsc(k)}</span><i style="--pct:${Math.round(p.buildMix[k].share * 100)}%"></i><b>${sdPct(p.buildMix[k].share)}</b></div>`
  ).join("");

  const lev = p.leverage.length
    ? p.leverage.map(x => `<div class="sdrow"><span class="nm">${sdEsc(x.name)}</span><span>${sdPct(x.exposure)} used vs ${sdPct(x.own)} field · ${sdFmt(x.ratio, 2)}x</span></div>`).join("")
    : `<p class="note">Nothing outside the band.</p>`;

  host.innerHTML =
    (p.flags.length ? `<div style="margin:10px 0">${p.flags.map(sdFlagHtml).join("")}</div>` : "") +
    `<details class="sdgroup" open><summary>Lineups · ${p.count}</summary>${rows}</details>` +
    `<details class="sdgroup"><summary>Captain exposure</summary>${cptBars}</details>` +
    `<details class="sdgroup"><summary>Build mix</summary>${mix}</details>` +
    `<details class="sdgroup"><summary>Leverage outliers · ${p.leverage.length}</summary>${lev}</details>`;
}

/* Import accepts DK ids or names, six per row. Unmatched cells are reported rather than
   dropped — a silently shortened lineup would validate as the wrong thing. */
function sdImportRows(text) {
  const pool = sdPool();
  const byId = {}, byName = {};
  pool.forEach(p => { byId[p.id] = p.id; byName[p.name.toLowerCase().replace(/[^a-z]/g, "")] = p.id; });
  const bad = [];
  const out = [];
  String(text || "").split(/\r?\n/).forEach((line, n) => {
    const cells = line.split(/[,\t]/).map(c => c.trim()).filter(Boolean);
    if (cells.length < 6) { if (cells.length) bad.push("row " + (n + 1) + ": " + cells.length + " players"); return; }
    const ids = cells.slice(0, 6).map(c => byId[c] || byName[c.toLowerCase().replace(/[^a-z]/g, "")] || null);
    const miss = cells.slice(0, 6).filter((c, i) => !ids[i]);
    if (miss.length) { bad.push("row " + (n + 1) + ": not on this slate — " + miss.join(", ")); return; }
    out.push({ id: "p" + (SD.portfolio.length + out.length + 1), cpt: ids[0], flex: ids.slice(1) });
  });
  return { lineups: out, errors: bad };
}

function sdExportCsv() {
  const by = {}; sdPool().forEach(p => by[p.id] = p);
  return ["CPT,FLEX,FLEX,FLEX,FLEX,FLEX"].concat(
    SD.portfolio.map(l => [l.cpt].concat(l.flex).map(id => (by[id] || {}).name || id).join(","))
  ).join("\n");
}

function sdBoot() {
  $("sdSlots").addEventListener("change", e => {
    const sel = e.target.closest("select[data-sd]");
    if (!sel) return;
    const k = sel.dataset.sd;
    if (k === "cpt") SD.lineup.cpt = sel.value; else SD.lineup.flex[+k] = sel.value;
    sdMeter();
  });
  ["sdFav", "sdSpread", "sdTotal"].forEach(id => $(id).addEventListener("change", () => {
    if (!$("sdResultCard").hidden) sdValidateCurrent();
    sdRenderPortfolio();
  }));
  $("sdCheck").addEventListener("click", sdValidateCurrent);
  $("sdClear").addEventListener("click", () => {
    SD.lineup = { cpt: "", flex: ["", "", "", "", ""] };
    $("sdResultCard").hidden = true;
    renderShowdown();
  });
  $("sdAdd").addEventListener("click", () => {
    if (!SD.lineup.cpt || SD.lineup.flex.some(x => !x)) { $("sdMsg").textContent = "Fill all six slots first."; $("sdMsg").className = "note warn"; return; }
    SD.portfolio.push({ id: "p" + (SD.portfolio.length + 1), cpt: SD.lineup.cpt, flex: SD.lineup.flex.slice() });
    $("sdMsg").textContent = "Added."; $("sdMsg").className = "note good";
    sdRenderPortfolio();
  });
  $("sdImport").addEventListener("click", () => {
    const res = sdImportRows($("sdPaste").value);
    res.lineups.forEach(l => SD.portfolio.push(l));
    $("sdPortMsg").textContent = (res.lineups.length ? "Imported " + res.lineups.length + ". " : "") +
      (res.errors.length ? "Skipped " + res.errors.length + " — " + res.errors.slice(0, 3).join("; ") : "");
    $("sdPortMsg").className = "note" + (res.errors.length ? " warn" : " good");
    if (res.lineups.length) $("sdPaste").value = "";
    sdRenderPortfolio();
  });
  $("sdValidateAll").addEventListener("click", sdRenderPortfolio);
  $("sdWipe").addEventListener("click", () => { SD.portfolio = []; $("sdPortMsg").textContent = ""; sdRenderPortfolio(); });
  $("sdExport").addEventListener("click", async () => {
    if (!SD.portfolio.length) { $("sdPortMsg").textContent = "Nothing to copy."; $("sdPortMsg").className = "note warn"; return; }
    try { await navigator.clipboard.writeText(sdExportCsv()); $("sdPortMsg").textContent = "Copied."; $("sdPortMsg").className = "note good"; }
    catch (_) { $("sdPortMsg").textContent = "Clipboard refused; select the rows in the box above instead."; $("sdPortMsg").className = "note warn"; $("sdPaste").value = sdExportCsv(); }
  });
}
""" + CTRL_END

BOOT_ANCHOR = "/* ---------------------------------------------------------------- wiring */"
once(s, BOOT_ANCHOR, "wiring section")
s = s.replace(BOOT_ANCHOR, "\n" + CTRL + "\n\n" + BOOT_ANCHOR, 1)

BOOT_CALL = "  renderStrip(); renderPool(); renderSolveStats(); renderLineups();"
if "\n  sdBoot();" not in s:
    once(s, BOOT_CALL, "boot render call")
    s = s.replace(BOOT_CALL, BOOT_CALL + "\n  sdBoot();", 1)

PAGE.write_text(s, encoding="utf-8")

for must in ['id="sh-showdown"', 'data-s="showdown"', "DDSDValidator", "renderShowdown", "sdBoot()"]:
    assert must in s, f"missing {must}"
print(f"dfs.html  {len(s):,} bytes")
