const assert=require('node:assert/strict'),D=require('./dfs-engine.js').DDFS;
const players=Array.from({length:8},(_,i)=>({name:'Synthetic '+i,pos:['QB','WR','RB','K'][i%4],team:i<4?'A':'B',opp:i<4?'B':'A',gid:0,sal:4000+i*400,proj:8+i,own:75,cptOwn:i===0?80:20/7}));
const one={ids:[0,1,2,4,5,6],cpt:0},two={ids:[1,2,3,4,6,7],cpt:7};
const cfg={site:'dk_showdown',sims:600,fieldSize:50,fieldSample:200,fieldMinSalary:0,entryFee:10,seed:123,payout:{kind:'flat',paidFrac:.4,rake:.2}};
const solo=D.simulate(players,[one],cfg),many=D.simulate(players,[two,one,{...one,ids:one.ids.slice().reverse()},...Array.from({length:65},()=>two)],cfg);
for(const key of ['mean','sd','ev','roi','cash','win','top1','top10','top1Share','dupes','meanRank','train','validation','ci'])assert.deepEqual(many.perLineup[1][key],solo.perLineup[0][key],key+' must not depend on other candidates');
assert.deepEqual(many.perLineup[1].validation,many.perLineup[2].validation);
assert.equal(many.meta.fieldSample,49);assert.equal(many.meta.candidateMode,'independent entries');
const tied=D.payoutFn({kind:'table',rows:[{from:1,to:1,prize:100},{from:2,to:2,prize:60},{from:3,to:3,prize:20}]},5,10);
assert.equal(tied.shared(0,2),60);assert.equal(tied.shared(1,3),20);
assert.deepEqual(D.tieOutcome(Float64Array.from([80,100,100,100]),100,5,tied),{above:0,tied:3,rank:2.5,prize:45});
assert.equal(D.tieOutcome(Float64Array.from([99.999,100.001,101,102]),100,5,tied).above,3,'Nearby scores are not histogram ties');
assert.throws(()=>D.payoutFn({kind:'table',rows:[{from:1,to:2,prize:10},{from:2,to:3,prize:5}]},10,1),/Overlapping/);
for(const n of [2,50,132000])assert.ok(Math.abs(D.payoutFn({kind:'param',paidFrac:.2,alpha:1.15,rake:.15},n,10).total-n*10*.85)<1e-6);
const duplicates=Array.from({length:49},()=>({...one,ids:one.ids.slice().reverse()}));
const allTied=D.simulate(players,[one,two],{...cfg,opponentLineups:duplicates});
assert.equal(allTied.perLineup[0].dupes,49);assert.ok(Math.abs(allTied.perLineup[0].roi+.2)<1e-12);
assert.equal(allTied.perLineup[0].meanRank,25.5);assert.ok(Math.abs(allTied.perLineup[0].firstShare-.02)<1e-12);
const samePlayersDifferentCaptain={...one,cpt:1};
const separated=D.simulate(players,[samePlayersDifferentCaptain],{...cfg,opponentLineups:duplicates});
assert.equal(separated.perLineup[0].dupes,0,'Captain identity belongs in the duplicate key');
const sampled=D.simulate(players,[one],{...cfg,fieldSize:132000,fieldSample:100,payout:{kind:'param'}});
assert.equal(sampled.perLineup[0].win,null);assert.equal(sampled.perLineup[0].roi,null);assert.equal(sampled.meta.top1Resolved,false);
assert.ok(sampled.perLineup[0].dupeCI[1]>0,'No observed copies is not proof of uniqueness');
assert.ok(D.wilson(0,800)[1]>0);assert.ok(D.wilson(8,800)[0]<.01&&D.wilson(8,800)[1]>.01);
const profiles=D.simulate(players,[one],{...cfg,contestProfiles:[{key:'milly',fieldSize:132000,entryFee:10,payout:{kind:'param'}},{key:'three',fieldSize:250,paidPlaces:75,entryFee:10,payout:{kind:'flat',paidFrac:.3,rake:.1}}]});
assert.equal(profiles.contests.three.meta.paidPlaces,75);assert.equal(profiles.contests.milly.meta.firstPlaceAvailable,false);
assert.equal(profiles.perLineup[0].validation.n,300);
// With the same six players in every field roster, captain choice is the only variable.
const six=players.slice(0,6).map((p,i)=>({...p,own:100,cptOwn:i===0?100:0}));
const captainOnly=D.simulate(six,[{ids:[0,1,2,3,4,5],cpt:0}],{...cfg,fieldSize:2000,fieldSample:1999});
assert.ok(captainOnly.perLineup[0].dupes>1850,'A 100%-CPT player must dominate captain selection, not total-own weighting');
console.log('Independent candidate ranks, CPT-aware fields, exact prize sharing, payout budget, sample-tail suppression and holdout statistics pass');
