import { chromiumExecutable, loadPlaywright } from "./playwright-loader.mjs";
import http from "http"; import fs from "fs"; import path from "path"; import { fileURLToPath } from "url";
const { chromium }=loadPlaywright(); let pass=0,fail=0; const ok=(n,c,x)=>c?(pass++,console.log("  ok   "+n)):(fail++,console.log("  FAIL "+n+(x?" — "+x:"")));
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const server=http.createServer((req,res)=>{const f=path.join(ROOT,decodeURIComponent(req.url.split("?")[0]));if(!f.startsWith(ROOT)||!fs.existsSync(f)){res.writeHead(404);return res.end("no");}res.writeHead(200,{"Content-Type":f.endsWith(".js")?"text/javascript":"text/html"});res.end(fs.readFileSync(f));});
await new Promise(r=>server.listen(8903,r)); const b=await chromium.launch({executablePath:chromiumExecutable(chromium),args:["--no-sandbox"]}); const p=await b.newPage();
await p.goto("http://127.0.0.1:8903/connect.html?next=bozo.html",{waitUntil:"load"});
await p.waitForURL("**/signon.html?next=bozo.html#connect",{timeout:4000}).catch(()=>{});
ok("connect.html redirects to the folded-in Connect sheet",/signon\.html/.test(p.url())&&p.url().includes("#connect"),p.url());
ok("query parameters survive the redirect",p.url().includes("next=bozo.html"),p.url());
const source=fs.readFileSync(path.join(ROOT,"connect.html"),"utf8");
ok("redirect has a canonical target",/rel="canonical"[^>]+signon\.html#connect/.test(source));
ok("redirect contains no identity or credential routes",!/auth\/|mcp-token|X-Dawg-Session/.test(source));
await b.close();server.close();console.log(`\n${pass} passed, ${fail} failed\n`);if(fail)process.exit(1);
